server:
  port: 8080

management:
  endpoints:
    health:
      show-details: "ALWAYS"
    web:
      exposure:
        include: "*"

spring:
  redis:
    sentinel:
      master: my_redis_master
      nodes:
        - 172.22.1.11
        - 172.22.1.21
        - 172.22.1.31
    lettuce:
      shutdown-timeout: 200ms
    port: 26379

debug: true
